# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-gaussian-explorer-web-eastus-dev-001

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: development

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./dist/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app-gaussian-explorer-web-eastus-dev-001
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-gaussian-explorer-web-eastus-dev-001

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_60FF1A1ED4BC4F5EB5F5A147C4A83C22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21487904256845C7885E092920A106BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C729985C686941FEAC6D541849BBD757 }}

      - name: 'Deploy to Azure Web App - East US Dev 001'
        id: deploy-to-webapp-eastus-dev-001
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-gaussian-explorer-web-eastus-dev-001'
          slot-name: 'Production'
          package: release.zip
          
